import type { Metadata } from 'next';
import { site, offers, contactUrl, productUrl } from '../_satellite-data';
import { industries, offerPlanning } from '../_planning-data';
const title = `${site.name}: industry applications and buying guide`;
const description = `Connect ${site.name.toLowerCase()} to industry requirements: inspection, training, Level III consulting, ERP, reporting, Digital Twin and Simulation. Build a usable project brief.`;
export const metadata: Metadata = {
  robots: { index: false, follow: true }, title: { absolute: title }, description, alternates: { canonical: site.domain+'/industries-and-applications' }, openGraph: { title, description, url: site.domain+'/industries-and-applications', type:'article' } };
export default function IndustryApplications() {
  return <div className="sat-home" data-expansion-release="planning-v1">
    <section className="sat-hero"><div className="sat-wrap"><p className="sat-eyebrow">{site.name} · Industry applications</p><h1>Connect the industry requirement to a defined NDT deliverable</h1><p className="sat-lead">{site.introduction}</p><p className="sat-note">This affiliated guide describes planning questions, not a claim of every industry accreditation, specialist method or onsite capability.</p><nav className="sat-offer-index" aria-label="Industry guide sections">{industries.map(industry => <a key={industry.id} href={'#'+industry.id}>{industry.name}</a>)}<a href="#service-selection">Product and service selection</a></nav></div></section>
    <section className="sat-wrap sat-section"><h2>Start from this resource’s technical question</h2><ul className="sat-checklist">{site.questions.map(question => <li key={question}>{question}</li>)}</ul><p className="sat-copy sat-boundary">{site.boundary}</p><p className="sat-copy">Use the industry briefs below to add the missing commercial detail: evidence available, required deliverable and the person authorised to accept it. The same asset may need inspection, reporting software and training, but those are separate scopes rather than an automatic bundle.</p></section>
    <div className="sat-wrap">{industries.map(industry => {const decision=offers.find(offer=>offer.key===industry.decision)!; const workflow=offers.find(offer=>offer.key===industry.workflow)!;return <section className="sat-section sat-offer-detail" id={industry.id} key={industry.id}><h2>{industry.name}</h2><p className="sat-copy">{industry.brief}</p><h3>Evidence to prepare</h3><p className="sat-copy">{industry.evidence}</p><div className="sat-grid"><article className="sat-card"><h3>Scope the immediate requirement</h3><p>{offerPlanning[decision.key][1]}</p><a className="sat-text-link" href={productUrl(decision)}>{decision.name} →</a></article><article className="sat-card"><h3>Consider the supporting workflow</h3><p>{offerPlanning[workflow.key][1]}</p><a className="sat-text-link" href={productUrl(workflow)}>{workflow.name} →</a></article></div><a className="sat-text-link" href={'/regions-and-project-planning#project-planner'}>Add your country, city and industry to the enquiry →</a></section>})}</div>
    <section className="sat-library" id="service-selection"><div className="sat-wrap sat-section"><h2>Choose among all seven core offers</h2><p className="sat-copy">Choose by the decision or workflow that needs support, not by the industry label alone. Digital Twin reporting and Practical NDT Simulation can be discussed individually or as ERP modules.</p><div className="sat-grid">{offers.map(offer => <article className="sat-card" key={offer.key}><h3>{offer.name}</h3><p>{offerPlanning[offer.key][1]}</p><a className="sat-text-link" href={productUrl(offer)}>Review the product or service →</a><a className="sat-button sat-button-secondary" href={contactUrl(offer, 'industry-'+offer.key)}>{offer.cta}</a></article>)}</div><p className="sat-copy">Additional needs: <a href="https://atlantisndt.com/3d-scanning-services">3D scanning for geometry capture</a> and <a href="https://atlantisndt.com/ndt-connect">NDT Connect</a>. Confirm their separate deliverables on the provider's main site.</p></div></section>
    <section className="sat-wrap sat-section"><h2>Method and procurement checklist</h2><p className="sat-copy">If the contract names UT, PAUT, TOFD, RT, MT, PT, ET or VT, include it with the material, geometry and examination objective. Naming a method here does not confirm that every service, course or simulation supports it. Ask the provider to confirm the precise application, required personnel and available capability.</p><ol className="sat-checklist"><li>Define the component, question, applicable documents and expected deliverable.</li><li>Agree method-specific qualifications, procedure authority and acceptance responsibility.</li><li>Separate field delivery, technical review, training and software implementation in the quotation.</li><li>Demonstrate a representative workflow or review a sample deliverable before expanding the scope.</li></ol><h3>Continue the topic on this site</h3><ul className="sat-library-list">{site.guides.map(guide => <li key={guide.href}><a href={guide.href}>{guide.label}</a></li>)}</ul><a className="sat-text-link" href="/atlantis-products-services">Full product and service comparison →</a></section>
  </div>;
}
