import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/deepwater" className="text-sm text-cyan-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/deepwater/rov-inspection-class-iii-vs-class-iv-which-tooling" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2024-09-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ROV Inspection Class III vs Class IV: Which Tooling Fits Which Scope</div>
          <div className="mt-2 text-sm text-gray-600">ROV Inspection Class III vs Class IV: Which Tooling Fits Which Scope</div>
        </a>
        <a href="/deepwater/subsea-pipeline-fjellsiganger-inspection-flooded-member" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-01-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Pipeline FMD: Detecting Flooded Members With Reliability</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Pipeline FMD: Detecting Flooded Members With Reliability</div>
        </a>
        <a href="/deepwater/cathodic-protection-survey-deepwater-cp-monitoring" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-06-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cathodic Protection Survey for Deepwater Assets: CP Monitoring Best Practice</div>
          <div className="mt-2 text-sm text-gray-600">Cathodic Protection Survey for Deepwater Assets: CP Monitoring Best Practice</div>
        </a>
        <a href="/deepwater/subsea-weld-flaw-sizing-with-paut-and-tofd" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-11-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Weld Flaw Sizing With PAUT and TOFD: Field Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Weld Flaw Sizing With PAUT and TOFD: Field Workflow</div>
        </a>
        <a href="/deepwater/fpso-hull-inspection-program-class-survey-coordination" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-03-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">FPSO Hull Inspection Program: Coordinating With Class Surveys</div>
          <div className="mt-2 text-sm text-gray-600">FPSO Hull Inspection Program: Coordinating With Class Surveys</div>
        </a>
        <a href="/deepwater/subsea-jumper-and-spool-inspection-2026-workflow" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-05-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Jumper and Spool Inspection: A 2026 Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Jumper and Spool Inspection: A 2026 Workflow</div>
        </a>
        <a href="/deepwater/subsea-manifold-anode-program-design" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-08-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Manifold Anode Program Design and Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Manifold Anode Program Design and Inspection</div>
        </a>
        <a href="/deepwater/rov-pilot-handoff-from-vessel-to-onshore-team" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-11-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ROV Pilot Hand-Off: From Vessel to Onshore Engineering Team</div>
          <div className="mt-2 text-sm text-gray-600">ROV Pilot Hand-Off: From Vessel to Onshore Engineering Team</div>
        </a>
        <a href="/deepwater/mattress-and-stabilization-cover-inspection-pipelines" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-02-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mattress and Stabilization Cover Inspection for Subsea Pipelines</div>
          <div className="mt-2 text-sm text-gray-600">Mattress and Stabilization Cover Inspection for Subsea Pipelines</div>
        </a>
        <a href="/deepwater/subsea-bolts-inspection-and-replacement-strategy" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-05-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Bolts: Inspection and Replacement Strategy for Critical Connectors</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Bolts: Inspection and Replacement Strategy for Critical Connectors</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-cyan-50 border border-cyan-100 rounded">
        <div className="text-sm uppercase tracking-wide text-cyan-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-cyan-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
