import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/methods" className="text-sm text-amber-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/methods/aws-d1-1-weld-acceptance-cracks-vs-incomplete-fusion" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2024-10-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">AWS D1.1 Weld Acceptance: Cracks vs Incomplete Fusion vs Slag</div>
          <div className="mt-2 text-sm text-gray-600">AWS D1.1 Weld Acceptance: Cracks vs Incomplete Fusion vs Slag</div>
        </a>
        <a href="/methods/phased-array-vs-radiography-girth-welds-which-finds-more" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-01-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Phased Array vs Radiography on Girth Welds: Which Finds More Defects?</div>
          <div className="mt-2 text-sm text-gray-600">Phased Array vs Radiography on Girth Welds: Which Finds More Defects?</div>
        </a>
        <a href="/methods/visual-weld-inspection-vt-pitfalls-cwi-experience" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-06-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Visual Weld Inspection (VT) Pitfalls: A CWI Field Perspective</div>
          <div className="mt-2 text-sm text-gray-600">Visual Weld Inspection (VT) Pitfalls: A CWI Field Perspective</div>
        </a>
        <a href="/methods/welder-qualification-vs-procedure-qualification-records" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-11-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Welder Qualification vs Procedure Qualification Records: Who Owns What?</div>
          <div className="mt-2 text-sm text-gray-600">Welder Qualification vs Procedure Qualification Records: Who Owns What?</div>
        </a>
        <a href="/methods/orbital-welding-inspection-semiconductor-pharma-piping" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-04-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Orbital Welding Inspection for Semiconductor & Pharma Piping</div>
          <div className="mt-2 text-sm text-gray-600">Orbital Welding Inspection for Semiconductor & Pharma Piping</div>
        </a>
        <a href="/methods/weld-mapping-as-a-quality-discipline" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-05-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Mapping as a Quality Discipline, Not a Paperwork Burden</div>
          <div className="mt-2 text-sm text-gray-600">Weld Mapping as a Quality Discipline, Not a Paperwork Burden</div>
        </a>
        <a href="/methods/weld-repair-vs-replace-decisions-on-pressure-piping" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-09-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Repair vs Replace Decisions on Pressure Piping</div>
          <div className="mt-2 text-sm text-gray-600">Weld Repair vs Replace Decisions on Pressure Piping</div>
        </a>
        <a href="/methods/duplex-stainless-weld-inspection-watchouts" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-12-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Duplex Stainless Steel Weld Inspection: Watchouts You Cannot Ignore</div>
          <div className="mt-2 text-sm text-gray-600">Duplex Stainless Steel Weld Inspection: Watchouts You Cannot Ignore</div>
        </a>
        <a href="/methods/weld-distortion-vs-residual-stress-different-problems" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-03-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Distortion vs Residual Stress: Two Different Problems With Different Cures</div>
          <div className="mt-2 text-sm text-gray-600">Weld Distortion vs Residual Stress: Two Different Problems With Different Cures</div>
        </a>
        <a href="/methods/weld-inspection-for-cryogenic-services-9-percent-nickel" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-05-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Inspection for Cryogenic Services: 9% Nickel and Beyond</div>
          <div className="mt-2 text-sm text-gray-600">Weld Inspection for Cryogenic Services: 9% Nickel and Beyond</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-amber-50 border border-amber-100 rounded">
        <div className="text-sm uppercase tracking-wide text-amber-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-amber-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
