import type { Metadata } from 'next';
import { site, offers, contactUrl, productUrl } from '../../_satellite-data';
import { article } from '../../_priority-article';
const route = '/guides/'+article.slug;
export const metadata: Metadata = {
  title: { absolute: article.title }, description: article.description,
  alternates: { canonical: site.domain+route }, robots: { index:true, follow:true },
  openGraph: { title:article.title,description:article.description,url:site.domain+route,type:'article' },
};
export default function PriorityArticle() {
  const primary=offers.find(offer=>offer.key===article.primaryOffer)!;
  const related=offers.filter(offer=>article.relatedOffers.includes(offer.key));
  return <article className="sat-home sat-editorial" data-editorial-release="editorial-v1">
    <header className="sat-hero"><div className="sat-wrap sat-reading"><p className="sat-eyebrow">{site.name} · Practical guide</p><h1>{article.title}</h1><p className="sat-lead">{article.description}</p><p className="sat-note">Educational workflow guidance. Examples are hypothetical, not reported client results. Applicable requirements and responsible technical authorities govern real work; this article does not establish service availability or approve a procedure.</p><nav className="sat-article-toc" aria-label="Article contents"><h2>In this guide</h2><ol>{article.sections.map((section,index)=><li key={section.heading}><a href={'#section-'+index}>{section.heading}</a></li>)}<li><a href="#checklist">Working checklist</a></li><li><a href="#references">References and scope</a></li></ol></nav></div></header>
    <div className="sat-wrap sat-reading" data-article-body="true">{article.sections.map((section,index)=><section className="sat-section sat-offer-detail" id={'section-'+index} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph,p)=><p className="sat-copy" key={p}>{paragraph}</p>)}{'bullets' in section&&section.bullets&&<ul className="sat-checklist">{section.bullets.map((item,i)=><li key={i}>{item}</li>)}</ul>}</section>)}</div>
    <aside className="sat-library"><div className="sat-wrap sat-reading sat-section"><h2>Apply the workflow to a real requirement</h2><p className="sat-copy">If the gaps identified in this guide require external support, review the scope of <a className="sat-text-link" href={productUrl(primary)}>{primary.name.toLowerCase()}</a>. A description is not a commitment that every application is supported: confirm deliverables, exclusions, credentials and available functionality before procurement.</p><p className="sat-copy">For a project-specific conversation, <a className="sat-text-link" href={contactUrl(primary,'editorial-enquiry')}>send a focused enquiry</a> with an anonymised example and the decision you need help making. Do not send confidential records until an appropriate channel is agreed.</p>{related.length>0&&<p className="sat-copy">Related workflows: {related.map((offer,index)=><span key={offer.key}>{index>0?' · ':''}<a className="sat-text-link" href={productUrl(offer)}>{offer.name.toLowerCase()}</a></span>)}.</p>}</div></aside>
    <section className="sat-wrap sat-reading sat-section" id="checklist"><h2>Working checklist</h2><ul className="sat-checklist">{article.checklist.map((item,index)=><li key={index}>{item}</li>)}</ul><p className="sat-copy">Use this as a discussion aid, not an approved technical procedure. Record unresolved questions and assign them to the responsible employer, customer or technical reviewer.</p></section>
    <section className="sat-wrap sat-reading sat-section" id="references"><h2>References and scope</h2><p className="sat-copy">The sources below provide context for the subject. The worked examples and administrative suggestions above are illustrative; they are not a reproduction of a standard or a substitute for its current requirements.</p><ul className="sat-checklist">{article.references.map(reference=><li key={reference.url}><a className="sat-text-link" href={reference.url}>{reference.label}</a></li>)}</ul><p className="sat-copy">For delivery considerations, use the <a className="sat-text-link" href="/regions-and-project-planning">regional project planner</a>. It prioritises the United States, then Canada, Europe, Australia, New Zealand, Singapore and Japan, followed by Middle East, India and Africa. A geographic reference is not evidence of a local office or an approved delivery scope.</p><a className="sat-text-link" href="/#resource-library">Back to the subject library →</a></section>
  </article>;
}
