import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/case-studies" className="text-sm text-orange-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/case-studies/in-line-inspection-tool-selection-mfl-vs-ut-vs-emat" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2024-08-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">In-Line Inspection Tool Selection: MFL vs UT vs EMAT</div>
          <div className="mt-2 text-sm text-gray-600">In-Line Inspection Tool Selection: MFL vs UT vs EMAT</div>
        </a>
        <a href="/case-studies/direct-assessment-eca-dca-ica-which-when" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2024-12-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Direct Assessment for Buried Pipelines: ECA, DCA, and ICA Compared</div>
          <div className="mt-2 text-sm text-gray-600">Direct Assessment for Buried Pipelines: ECA, DCA, and ICA Compared</div>
        </a>
        <a href="/case-studies/crack-management-program-pipeline-asme-b31-8s" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-04-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipeline Crack Management Program: Aligning with ASME B31.8S</div>
          <div className="mt-2 text-sm text-gray-600">Pipeline Crack Management Program: Aligning with ASME B31.8S</div>
        </a>
        <a href="/case-studies/pipeline-coating-disbondment-detection-tools" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-09-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipeline Coating Disbondment: Detection Tools and Field Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Pipeline Coating Disbondment: Detection Tools and Field Workflow</div>
        </a>
        <a href="/case-studies/pipeline-rehabilitation-options-composite-vs-steel-sleeve" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-04-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipeline Rehabilitation Options: Composite Sleeves vs Steel Sleeves</div>
          <div className="mt-2 text-sm text-gray-600">Pipeline Rehabilitation Options: Composite Sleeves vs Steel Sleeves</div>
        </a>
        <a href="/case-studies/ili-data-validation-workflow-anomaly-truth-table" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-05-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ILI Data Validation Workflow: Building an Anomaly Truth Table</div>
          <div className="mt-2 text-sm text-gray-600">ILI Data Validation Workflow: Building an Anomaly Truth Table</div>
        </a>
        <a href="/case-studies/pipeline-girth-weld-quality-management-eca-strain" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-08-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipeline Girth Weld Quality Management: ECA, Strain, and Construction Reality</div>
          <div className="mt-2 text-sm text-gray-600">Pipeline Girth Weld Quality Management: ECA, Strain, and Construction Reality</div>
        </a>
        <a href="/case-studies/class-location-changes-mop-and-the-inspector-implications" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-11-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Class Location Changes, MOP, and the Inspector Implications</div>
          <div className="mt-2 text-sm text-gray-600">Class Location Changes, MOP, and the Inspector Implications</div>
        </a>
        <a href="/case-studies/pipeline-leak-detection-program-design-cpm-vs-extended" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-02-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipeline Leak Detection Program Design: CPM vs Extended Sensor Approaches</div>
          <div className="mt-2 text-sm text-gray-600">Pipeline Leak Detection Program Design: CPM vs Extended Sensor Approaches</div>
        </a>
        <a href="/case-studies/integrity-verification-process-post-spike-hydrotest" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-05-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Integrity Verification Process: Post-Spike Hydrotest Strategy</div>
          <div className="mt-2 text-sm text-gray-600">Integrity Verification Process: Post-Spike Hydrotest Strategy</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-orange-50 border border-orange-100 rounded">
        <div className="text-sm uppercase tracking-wide text-orange-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-orange-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
