import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/renewables" className="text-sm text-green-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/renewables/wind-turbine-foundation-grout-inspection-offshore" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2024-10-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wind Turbine Foundation Grout Inspection (Offshore Monopiles)</div>
          <div className="mt-2 text-sm text-gray-600">Wind Turbine Foundation Grout Inspection (Offshore Monopiles)</div>
        </a>
        <a href="/renewables/green-hydrogen-pipeline-inspection-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-03-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Green Hydrogen Pipeline Inspection: New Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Green Hydrogen Pipeline Inspection: New Considerations</div>
        </a>
        <a href="/renewables/csp-receiver-tube-inspection-concentrated-solar" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-08-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">CSP Receiver Tube Inspection for Concentrated Solar Plants</div>
          <div className="mt-2 text-sm text-gray-600">CSP Receiver Tube Inspection for Concentrated Solar Plants</div>
        </a>
        <a href="/renewables/geothermal-well-casing-corrosion-and-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-12-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Geothermal Well Casing Corrosion and Inspection Strategy</div>
          <div className="mt-2 text-sm text-gray-600">Geothermal Well Casing Corrosion and Inspection Strategy</div>
        </a>
        <a href="/renewables/wind-blade-leading-edge-erosion-detection-and-repair" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2026-04-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wind Blade Leading Edge Erosion: Detection and Repair</div>
          <div className="mt-2 text-sm text-gray-600">Wind Blade Leading Edge Erosion: Detection and Repair</div>
        </a>
        <a href="/renewables/floating-offshore-wind-inspection-emerging-practice" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-05-27</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Floating Offshore Wind Inspection: Emerging Practice for FOWT Programs</div>
          <div className="mt-2 text-sm text-gray-600">Floating Offshore Wind Inspection: Emerging Practice for FOWT Programs</div>
        </a>
        <a href="/renewables/hydrogen-storage-vessel-inspection-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-09-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Hydrogen Storage Vessel Inspection Considerations Across Pressure Classes</div>
          <div className="mt-2 text-sm text-gray-600">Hydrogen Storage Vessel Inspection Considerations Across Pressure Classes</div>
        </a>
        <a href="/renewables/pv-module-electroluminescence-and-infrared-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-12-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">PV Module Electroluminescence and Infrared Inspection in the Field</div>
          <div className="mt-2 text-sm text-gray-600">PV Module Electroluminescence and Infrared Inspection in the Field</div>
        </a>
        <a href="/renewables/wind-turbine-gearbox-and-bearing-condition-monitoring" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2026-03-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wind Turbine Gearbox and Bearing Condition Monitoring With NDT Overlap</div>
          <div className="mt-2 text-sm text-gray-600">Wind Turbine Gearbox and Bearing Condition Monitoring With NDT Overlap</div>
        </a>
        <a href="/renewables/tidal-and-wave-energy-asset-inspection-introduction" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2026-05-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tidal and Wave Energy Asset Inspection: An Introduction</div>
          <div className="mt-2 text-sm text-gray-600">Tidal and Wave Energy Asset Inspection: An Introduction</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-green-50 border border-green-100 rounded">
        <div className="text-sm uppercase tracking-wide text-green-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-green-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
