import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/rail" className="text-sm text-orange-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/rail/rail-flaw-detection-vehicle-types-and-tradeoffs" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2024-09-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Flaw Detection Vehicles: Types, Speeds, and Trade-Offs</div>
          <div className="mt-2 text-sm text-gray-600">Rail Flaw Detection Vehicles: Types, Speeds, and Trade-Offs</div>
        </a>
        <a href="/rail/rolling-stock-wheel-set-ndt-paut-and-mt" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-02-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rolling Stock Wheel Set NDT: PAUT and MT in Practice</div>
          <div className="mt-2 text-sm text-gray-600">Rolling Stock Wheel Set NDT: PAUT and MT in Practice</div>
        </a>
        <a href="/rail/thermite-weld-inspection-on-continuous-welded-rail" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-07-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Thermite Weld Inspection on Continuous Welded Rail</div>
          <div className="mt-2 text-sm text-gray-600">Thermite Weld Inspection on Continuous Welded Rail</div>
        </a>
        <a href="/rail/rail-corrosion-fatigue-detection-rcf-cracking" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-12-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Rolling Contact Fatigue (RCF): Detection and Mitigation</div>
          <div className="mt-2 text-sm text-gray-600">Rail Rolling Contact Fatigue (RCF): Detection and Mitigation</div>
        </a>
        <a href="/rail/rail-bridge-truss-inspection-aar-mra" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-04-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Bridge Truss Inspection: AAR and Operator Practice</div>
          <div className="mt-2 text-sm text-gray-600">Rail Bridge Truss Inspection: AAR and Operator Practice</div>
        </a>
        <a href="/rail/rail-track-bolt-and-fishplate-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-05-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Track Bolt and Fishplate Inspection in Continuous Service</div>
          <div className="mt-2 text-sm text-gray-600">Rail Track Bolt and Fishplate Inspection in Continuous Service</div>
        </a>
        <a href="/rail/rail-axle-ultrasonic-inspection-procedure" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-09-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Axle Ultrasonic Inspection Procedure and Probe Selection</div>
          <div className="mt-2 text-sm text-gray-600">Rail Axle Ultrasonic Inspection Procedure and Probe Selection</div>
        </a>
        <a href="/rail/frog-and-switch-component-inspection-on-mainline-rail" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-12-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Frog and Switch Component Inspection on Mainline Rail</div>
          <div className="mt-2 text-sm text-gray-600">Frog and Switch Component Inspection on Mainline Rail</div>
        </a>
        <a href="/rail/rail-coach-and-locomotive-shell-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-03-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Coach and Locomotive Shell Inspection: Aluminum vs Steel</div>
          <div className="mt-2 text-sm text-gray-600">Rail Coach and Locomotive Shell Inspection: Aluminum vs Steel</div>
        </a>
        <a href="/rail/rail-bearing-and-axlebox-ndt-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-05-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rail Bearing and Axlebox NDT Program</div>
          <div className="mt-2 text-sm text-gray-600">Rail Bearing and Axlebox NDT Program</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-orange-50 border border-orange-100 rounded">
        <div className="text-sm uppercase tracking-wide text-orange-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-orange-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
