import type { Metadata } from 'next';
import { site, offers, contactUrl, productUrl } from '../_satellite-data';

const title = `Atlantis products and services for ${site.name}`;
const description = `Compare training, inspection, Level III consulting, ERP, NDT reporting, Digital Twin reporting and Simulation from ${site.name}. Prepare a focused enquiry.`;
export const metadata: Metadata = {
  title: { absolute: title }, description,
  alternates: { canonical: site.domain + '/atlantis-products-services' },
  openGraph: { title, description, url: site.domain + '/atlantis-products-services', type: 'website' },
};

const briefs: Record<string, { need: string; prepare: string[]; boundary: string }> = {
  training: { need: 'Build technician knowledge or plan an employer-sponsored learning programme.', prepare: ['Method and target level; current training and experience records.', 'Number of learners, delivery format, country and preferred dates.', 'The employer written practice or qualification scheme the training must support.'], boundary: 'NDT training is not API training. Completing a course alone does not establish personnel certification or replace required experience, examinations and employer responsibilities.' },
  inspection: { need: 'Examine a component or asset and agree how findings will be reported.', prepare: ['Material, geometry, access, asset location and operating conditions.', 'Required method, examination extent, acceptance criteria and governing documents.', 'Work window, site access requirements and report deliverables.'], boundary: 'Confirm qualified personnel, equipment, permits and local delivery before scheduling. A general method guide is not a project procedure or evidence that every method is available at every location.' },
  consulting: { need: 'Resolve a procedure, personnel-qualification or technical oversight requirement.', prepare: ['Applicable codes, customer specifications and employer written practice.', 'Existing procedures or records, the review question and required approval authority.', 'Methods involved, audit or project deadline and expected deliverable.'], boundary: 'Agree the responsible Level III role, method-specific credentials and scope of review. Consulting does not imply accreditation, regulatory approval or automatic acceptance by a customer.' },
  erp: { need: 'Connect inspection-company operations that currently sit in separate spreadsheets or systems.', prepare: ['A sample workflow from enquiry and quotation through scheduling, reports and invoicing.', 'Technician and calibration records, existing systems and migration requirements.', 'Users, locations, access roles, integrations and implementation priorities.'], boundary: 'Request a workflow demonstration and a scoped proposal. Confirm available features, licensing, deployment, integrations and support; do not assume an integration or compliance outcome from a product description.' },
  reporting: { need: 'Improve field data capture, review and issue of inspection reports.', prepare: ['An anonymised report template and the methods or inspection types to cover.', 'Required units, traceability, review steps, signatures and revision control.', 'Field connectivity, export formats and links to existing asset or job records.'], boundary: 'Discuss standalone reporting or an ERP module. A reporting template does not itself determine acceptance criteria or certify the inspection; technical review and approved procedures remain necessary.' },
  twin: { need: 'Review inspection findings and history in the context of an asset model.', prepare: ['The asset type and available model, drawings or geometry.', 'Inspection records, location identifiers and the way findings should be mapped.', 'The review task, expected outputs, access roles and integration requirements.'], boundary: 'Digital Twin-based NDT reporting can be discussed as standalone software or an ERP module. Confirm supported formats and data preparation; a model does not replace inspection or engineering assessment.' },
  simulation: { need: 'Support practical learning scenarios and discussion before or alongside supervised work.', prepare: ['Learner experience, target NDT methods and learning objectives.', 'Instructor-led or individual use, available devices and expected cohort size.', 'Required scenarios, assessment workflow and training-system integration.'], boundary: 'Practical NDT Simulation can be discussed as standalone software or an ERP module. Confirm supported scenarios in a demo. Simulation does not replace required hands-on experience, examinations or personnel certification.' },
};

export default function ProductsServices() {
  return <div className="sat-home" data-coverage-release="all-offers-v1">
    <section className="sat-hero"><div className="sat-wrap">
      <p className="sat-eyebrow">{site.name} · Product and service guide</p>
      <h1>Find the right Atlantis product or service</h1>
      <p className="sat-lead">For {site.audience.toLowerCase()}, the first question is what needs to change: personnel knowledge, an inspection deliverable, technical oversight or the systems that hold the work together. This guide covers the complete core range, with the options most relevant to this resource listed first.</p>
      <p className="sat-note">This is an Atlantis-owned resource, not an independent supplier ranking. Product information and enquiries continue on atlantisndt.com.</p>
      <nav className="sat-offer-index" aria-label="Jump to a product or service">{offers.map(offer => <a key={offer.key} href={'#'+offer.key}>{offer.name}</a>)}<a href="#additional-options">Additional options</a></nav>
    </div></section>
    <section className="sat-wrap sat-section"><h2>Start with your project brief</h2><p className="sat-copy">{site.introduction}</p><ul className="sat-checklist">{site.questions.map(question => <li key={question}>{question}</li>)}</ul><p className="sat-copy sat-boundary">{site.boundary}</p></section>
    <div className="sat-wrap">{offers.map(offer => <section className="sat-section sat-offer-detail" id={offer.key} key={offer.key} aria-labelledby={offer.key+'-title'}>
      <p className="sat-eyebrow">When to consider this option</p><h2 id={offer.key+'-title'}>{offer.name}</h2><p className="sat-copy">{briefs[offer.key].need} {offer.description}</p>
      <h3>Prepare for the conversation</h3><ul className="sat-checklist">{briefs[offer.key].prepare.map(item => <li key={item}>{item}</li>)}</ul><p className="sat-copy">{briefs[offer.key].boundary}</p>
      <div className="sat-actions"><a className="sat-button" href={contactUrl(offer, 'catalogue-'+offer.key)}>{offer.cta}</a><a className="sat-button sat-button-secondary" href={productUrl(offer)}>Explore {offer.name}</a></div>
    </section>)}</div>
    <section className="sat-library" id="additional-options"><div className="sat-wrap sat-section"><h2>Additional Atlantis options</h2><p className="sat-copy">These are separate enquiries, not prerequisites for the core offers above.</p><div className="sat-grid">
      <article className="sat-card"><h3>3D scanning services</h3><p>Discuss geometry capture when your project requires an as-built model. Specify the asset, intended use, access and required accuracy. Scanning and NDT inspection answer different questions; confirm deliverables and onsite availability separately.</p><a className="sat-text-link" href="https://atlantisndt.com/3d-scanning-services">Explore 3D scanning services →</a></article>
      <article className="sat-card"><h3>NDT Connect</h3><p>Explore the Atlantis NDT Connect platform for connecting inspection professionals and organisations. Check current participation requirements and opportunities on the main site. A platform listing is not a guarantee of personnel qualification, employment or project availability.</p><a className="sat-text-link" href="https://atlantisndt.com/ndt-connect">Explore NDT Connect →</a></article>
    </div></div></section>
    <section className="sat-wrap sat-section"><h2>Location, methods and next steps</h2><p className="sat-copy">Include your country and the actual project location. US requirements are the first priority, followed by Canada, Europe, Australia, New Zealand, Singapore and Japan, then Middle East, India and Africa. Discuss remote delivery, onsite mobilisation, language, time zones and applicable approvals before agreeing a scope. This resource does not imply a local office.</p><p className="sat-copy">For method-specific enquiries, name the method and application rather than assuming every offer has identical coverage. The Atlantis team should confirm the relevant inspection capability, training course, report template or simulation scenario. Send an anonymised example where practical; agree a suitable channel before sharing confidential project records.</p><a className="sat-text-link" href="/#resource-library">Return to the {site.name} resource library →</a></section>
  </div>;
}
