import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/tanks" className="text-sm text-cyan-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/tanks/api-653-out-of-service-internal-inspection-checklist" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2024-09-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 653 Out-of-Service Internal Inspection Checklist</div>
          <div className="mt-2 text-sm text-gray-600">API 653 Out-of-Service Internal Inspection Checklist</div>
        </a>
        <a href="/tanks/tank-floor-mfl-vs-paut-which-fits-the-job" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-01-28</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Floor MFL vs PAUT: Which Method Fits the Job?</div>
          <div className="mt-2 text-sm text-gray-600">Tank Floor MFL vs PAUT: Which Method Fits the Job?</div>
        </a>
        <a href="/tanks/tank-shell-thickness-program-with-out-of-service-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-06-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Shell Thickness Program With and Without Out-of-Service Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Tank Shell Thickness Program With and Without Out-of-Service Inspection</div>
        </a>
        <a href="/tanks/floating-roof-seal-inspection-and-leak-detection" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-11-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Floating Roof Seal Inspection and Leak Detection</div>
          <div className="mt-2 text-sm text-gray-600">Floating Roof Seal Inspection and Leak Detection</div>
        </a>
        <a href="/tanks/soil-side-corrosion-on-tank-floors-and-detection" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-04-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Soil-Side Corrosion on Tank Floors and How to Detect It</div>
          <div className="mt-2 text-sm text-gray-600">Soil-Side Corrosion on Tank Floors and How to Detect It</div>
        </a>
        <a href="/tanks/tank-roof-pontoon-leak-detection-vacuum-box" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-05-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Roof Pontoon Leak Detection With Vacuum Box and Tracer Gas</div>
          <div className="mt-2 text-sm text-gray-600">Tank Roof Pontoon Leak Detection With Vacuum Box and Tracer Gas</div>
        </a>
        <a href="/tanks/tank-secondary-containment-inspection-and-integrity" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-09-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Secondary Containment Inspection and Integrity</div>
          <div className="mt-2 text-sm text-gray-600">Tank Secondary Containment Inspection and Integrity</div>
        </a>
        <a href="/tanks/api-650-construction-ndt-acceptance-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2025-12-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 650 Construction NDT Acceptance: A Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">API 650 Construction NDT Acceptance: A Walkthrough</div>
        </a>
        <a href="/tanks/asphalt-and-fuel-oil-tank-inspection-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-03-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Asphalt and Fuel Oil Tank Inspection Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Asphalt and Fuel Oil Tank Inspection Considerations</div>
        </a>
        <a href="/tanks/tank-relocation-and-reerection-ndt-rules" className="block p-4 bg-white border border-gray-200 rounded hover:border-cyan-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-cyan-600">2026-05-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Relocation and Re-Erection NDT Rules</div>
          <div className="mt-2 text-sm text-gray-600">Tank Relocation and Re-Erection NDT Rules</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-cyan-50 border border-cyan-100 rounded">
        <div className="text-sm uppercase tracking-wide text-cyan-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-cyan-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
