import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/plant" className="text-sm text-yellow-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/plant/boiler-tube-inspection-program-for-fossil-plants" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2024-09-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Boiler Tube Inspection Program for Fossil Plants</div>
          <div className="mt-2 text-sm text-gray-600">Boiler Tube Inspection Program for Fossil Plants</div>
        </a>
        <a href="/plant/turbine-blade-root-inspection-eddy-current-and-paut" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-03-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Turbine Blade Root Inspection: Eddy Current and PAUT in Practice</div>
          <div className="mt-2 text-sm text-gray-600">Turbine Blade Root Inspection: Eddy Current and PAUT in Practice</div>
        </a>
        <a href="/plant/gas-turbine-hot-section-inspection-borescope-and-fpi" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-08-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Gas Turbine Hot Section Inspection: Borescope and FPI in Practice</div>
          <div className="mt-2 text-sm text-gray-600">Gas Turbine Hot Section Inspection: Borescope and FPI in Practice</div>
        </a>
        <a href="/plant/condenser-tube-inspection-for-power-plants" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-12-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Condenser Tube Inspection for Power Plants: A Practical Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Condenser Tube Inspection for Power Plants: A Practical Workflow</div>
        </a>
        <a href="/plant/inspection-of-wind-turbine-tower-flange-bolts" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2026-04-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inspection of Wind Turbine Tower Flange Bolts: Why It Keeps Surprising People</div>
          <div className="mt-2 text-sm text-gray-600">Inspection of Wind Turbine Tower Flange Bolts: Why It Keeps Surprising People</div>
        </a>
        <a href="/plant/hrsg-tube-inspection-for-combined-cycle-plants" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-05-24</div>
          <div className="mt-1 text-base font-semibold text-gray-900">HRSG Tube Inspection for Combined Cycle Plants</div>
          <div className="mt-2 text-sm text-gray-600">HRSG Tube Inspection for Combined Cycle Plants</div>
        </a>
        <a href="/plant/steam-piping-creep-damage-monitoring-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-09-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Steam Piping Creep Damage Monitoring Program</div>
          <div className="mt-2 text-sm text-gray-600">Steam Piping Creep Damage Monitoring Program</div>
        </a>
        <a href="/plant/cooling-tower-structural-inspection-fiberglass-and-concrete" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2025-12-01</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cooling Tower Structural Inspection: Fiberglass and Concrete Components</div>
          <div className="mt-2 text-sm text-gray-600">Cooling Tower Structural Inspection: Fiberglass and Concrete Components</div>
        </a>
        <a href="/plant/generator-stator-and-rotor-ndt-techniques" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2026-03-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Generator Stator and Rotor NDT Techniques</div>
          <div className="mt-2 text-sm text-gray-600">Generator Stator and Rotor NDT Techniques</div>
        </a>
        <a href="/plant/solar-pv-tracker-and-mounting-structure-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-yellow-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-yellow-600">2026-05-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Solar PV Tracker and Mounting Structure Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Solar PV Tracker and Mounting Structure Inspection</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-yellow-50 border border-yellow-100 rounded">
        <div className="text-sm uppercase tracking-wide text-yellow-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-yellow-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
