import type { Metadata } from 'next';
import { site, offers, contactUrl, productUrl } from '../_satellite-data';
import { regions, offerPlanning } from '../_planning-data';
import ProjectPlanner from '../_project-planner';
const title = `${site.name}: US and international project planning`;
const description = `Plan ${site.name.toLowerCase()} requirements by location, delivery format and service. US-first guidance, international project briefs and an Atlantis enquiry planner.`;
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: site.domain+'/regions-and-project-planning' }, openGraph: { title, description, url: site.domain+'/regions-and-project-planning', type:'article' } };
export default function RegionalPlanning() {
  return <div className="sat-home" data-expansion-release="planning-v1">
    <section className="sat-hero"><div className="sat-wrap"><p className="sat-eyebrow">{site.name} · Regional planning</p><h1>Plan the requirement before choosing the delivery location</h1><p className="sat-lead">{site.introduction}</p><p className="sat-note">An Atlantis-owned planning resource. Locations below help structure an enquiry; they are not a list of Atlantis offices, completed projects or guaranteed service areas.</p><nav className="sat-offer-index" aria-label="Regional guide sections"><a href="#project-planner">Build your enquiry</a>{regions.map((region,index) => <a key={region.name} href={'#region-'+index}>{region.name}</a>)}<a href="/industries-and-applications">Industry guide</a></nav></div></section>
    <section className="sat-wrap sat-section"><h2>A location-ready brief for {site.audience.toLowerCase()}</h2><ul className="sat-checklist">{site.questions.map(question => <li key={question}>{question}</li>)}<li>Which country and actual worksite determine access, working language, time zone and customer approval?</li><li>Which tasks can be reviewed remotely, and which require personnel, equipment or supervised practice onsite?</li></ul><p className="sat-copy sat-boundary">{site.boundary}</p><p className="sat-copy">Start with one representative application and its governing documents. A regional procurement label is not enough to establish personnel eligibility, approval authority or delivery availability.</p></section>
    <div className="sat-wrap" id="project-planner"><ProjectPlanner /></div>
    <div className="sat-wrap">{regions.map((region,index) => <section className="sat-section sat-offer-detail" key={region.name} id={'region-'+index}><p className="sat-eyebrow">{region.priority}</p><h2>{region.name}</h2><p className="sat-copy">{region.brief}</p><h3>What to settle before requesting a date or quotation</h3><ul className="sat-checklist">{region.prepare.map(item => <li key={item}>{item}</li>)}</ul><details className="sat-city-note"><summary>City and worksite details</summary><p>{region.cities} These are examples for describing project locations, not service-availability claims. Any other city can be entered in the planner. Use the actual worksite city; share precise access details directly with the team once scope and an appropriate information channel are agreed.</p></details><a className="sat-text-link" href="#project-planner">Prepare an enquiry for this location →</a></section>)}</div>
    <section className="sat-library"><div className="sat-wrap sat-section"><h2>Every core offer, with the right project context</h2><div className="sat-grid">{offers.map(offer => <article className="sat-card" key={offer.key}><h3>{offer.name}</h3><p>{offerPlanning[offer.key][1]}</p><a className="sat-text-link" href={productUrl(offer)}>Explore {offer.name} →</a><a className="sat-button sat-button-secondary" href={contactUrl(offer, 'regional-'+offer.key)}>{offer.cta}</a></article>)}</div><p className="sat-copy">For <a href="https://atlantisndt.com/3d-scanning-services">3D scanning</a> or <a href="https://atlantisndt.com/ndt-connect">NDT Connect</a>, use the relevant product page to confirm scope. These additional options are not prerequisites for an NDT enquiry.</p></div></section>
    <section className="sat-wrap sat-section"><h2>Check before you commit</h2><p className="sat-copy">Ask for a written scope separating deliverables, exclusions, delivery location, prerequisites, review responsibilities and fees. For training, course attendance is not personnel certification. For software, confirm supported workflows, integrations and support. For field work, confirm the specific personnel, equipment and required approvals.</p><a className="sat-text-link" href="/atlantis-products-services">Compare products and services →</a></section>
  </div>;
}
