import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/operation" className="text-sm text-red-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/operation/api-510-internal-vs-external-inspection-decision" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2024-09-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 510 Internal vs External Inspection: Choosing the Right Approach</div>
          <div className="mt-2 text-sm text-gray-600">API 510 Internal vs External Inspection: Choosing the Right Approach</div>
        </a>
        <a href="/operation/asme-section-viii-fabrication-ndt-requirements-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-02-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASME Section VIII Fabrication NDT Requirements: A Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">ASME Section VIII Fabrication NDT Requirements: A Walkthrough</div>
        </a>
        <a href="/operation/reformer-tubes-creep-damage-monitoring-strategies" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-07-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Reformer Tubes Creep Damage Monitoring: Strategies That Work</div>
          <div className="mt-2 text-sm text-gray-600">Reformer Tubes Creep Damage Monitoring: Strategies That Work</div>
        </a>
        <a href="/operation/corrosion-monitoring-locations-cml-selection-guide" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-12-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Corrosion Monitoring Locations (CMLs): A Selection Guide for Pressure Vessels</div>
          <div className="mt-2 text-sm text-gray-600">Corrosion Monitoring Locations (CMLs): A Selection Guide for Pressure Vessels</div>
        </a>
        <a href="/operation/long-range-ut-screening-pressure-vessels" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-04-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Long-Range UT Screening for Pressure Vessels: When It Adds Real Value</div>
          <div className="mt-2 text-sm text-gray-600">Long-Range UT Screening for Pressure Vessels: When It Adds Real Value</div>
        </a>
        <a href="/operation/pressure-vessel-nozzle-weld-inspection-deep-dive" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-05-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pressure Vessel Nozzle Weld Inspection: A Practical Deep Dive</div>
          <div className="mt-2 text-sm text-gray-600">Pressure Vessel Nozzle Weld Inspection: A Practical Deep Dive</div>
        </a>
        <a href="/operation/on-stream-inspection-with-pulsed-eddy-current" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-08-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">On-Stream Vessel Inspection With Pulsed Eddy Current: Where It Actually Works</div>
          <div className="mt-2 text-sm text-gray-600">On-Stream Vessel Inspection With Pulsed Eddy Current: Where It Actually Works</div>
        </a>
        <a href="/operation/pressure-vessel-thermal-relief-valve-and-prv-tie-ins" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-11-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pressure Vessel Thermal Relief and PRV Tie-In Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Pressure Vessel Thermal Relief and PRV Tie-In Inspection</div>
        </a>
        <a href="/operation/low-temperature-vessel-impact-test-requirements" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-02-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Low-Temperature Vessel Impact Test Requirements: ASME UCS-66 Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">Low-Temperature Vessel Impact Test Requirements: ASME UCS-66 Walkthrough</div>
        </a>
        <a href="/operation/rerating-pressure-vessels-when-it-is-worth-it" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-05-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Rerating Pressure Vessels: When It Is Worth It (and When It Is Not)</div>
          <div className="mt-2 text-sm text-gray-600">Rerating Pressure Vessels: When It Is Worth It (and When It Is Not)</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-red-50 border border-red-100 rounded">
        <div className="text-sm uppercase tracking-wide text-red-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-red-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
