import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/inspect" className="text-sm text-amber-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/inspect/cwi-vs-cswip-vs-iwi-which-cert-for-which-market" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2024-08-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">CWI vs CSWIP vs IWI: Which Cert Fits Which Market?</div>
          <div className="mt-2 text-sm text-gray-600">CWI vs CSWIP vs IWI: Which Cert Fits Which Market?</div>
        </a>
        <a href="/inspect/visual-weld-acceptance-by-code-asme-vs-aws" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-02-01</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Visual Weld Acceptance by Code: ASME Section IX vs AWS D1.1</div>
          <div className="mt-2 text-sm text-gray-600">Visual Weld Acceptance by Code: ASME Section IX vs AWS D1.1</div>
        </a>
        <a href="/inspect/weld-procedure-qualification-record-pqr-from-zero" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-06-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Procedure Qualification Record (PQR) From Zero</div>
          <div className="mt-2 text-sm text-gray-600">Weld Procedure Qualification Record (PQR) From Zero</div>
        </a>
        <a href="/inspect/welding-distortion-control-on-thin-plate-fabrication" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-10-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Welding Distortion Control on Thin-Plate Fabrication</div>
          <div className="mt-2 text-sm text-gray-600">Welding Distortion Control on Thin-Plate Fabrication</div>
        </a>
        <a href="/inspect/macro-etch-test-on-welds-what-it-actually-shows" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-03-28</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Macro-Etch Test on Welds: What It Actually Shows You</div>
          <div className="mt-2 text-sm text-gray-600">Macro-Etch Test on Welds: What It Actually Shows You</div>
        </a>
        <a href="/inspect/aws-d17-1-aerospace-fusion-welding-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-05-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">AWS D17.1 Aerospace Fusion Welding: A Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">AWS D17.1 Aerospace Fusion Welding: A Walkthrough</div>
        </a>
        <a href="/inspect/iwip-and-iwip-c-paths-vs-cwi-comparison" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-09-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">IWIP and IWIP-C Paths vs CWI: Comparison for Inspector Choice</div>
          <div className="mt-2 text-sm text-gray-600">IWIP and IWIP-C Paths vs CWI: Comparison for Inspector Choice</div>
        </a>
        <a href="/inspect/gtaw-vs-gmaw-process-influence-on-weld-quality" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-12-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">GTAW vs GMAW Process Influence on Weld Quality and Inspection Findings</div>
          <div className="mt-2 text-sm text-gray-600">GTAW vs GMAW Process Influence on Weld Quality and Inspection Findings</div>
        </a>
        <a href="/inspect/underwater-welding-inspection-class-and-standard" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-03-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Underwater Welding Inspection: Class and Standard Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Underwater Welding Inspection: Class and Standard Considerations</div>
        </a>
        <a href="/inspect/weld-acceptance-on-coated-and-cladded-components" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-05-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Weld Acceptance on Coated and Cladded Components</div>
          <div className="mt-2 text-sm text-gray-600">Weld Acceptance on Coated and Cladded Components</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-amber-50 border border-amber-100 rounded">
        <div className="text-sm uppercase tracking-wide text-amber-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-amber-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
