import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/sectors" className="text-sm text-amber-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/sectors/upstream-midstream-downstream-inspection-budget-allocation" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2024-10-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Upstream vs Midstream vs Downstream: Where Inspection Budget Actually Goes</div>
          <div className="mt-2 text-sm text-gray-600">Upstream vs Midstream vs Downstream: Where Inspection Budget Actually Goes</div>
        </a>
        <a href="/sectors/crude-oil-storage-tank-inspection-api-653-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-02-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Crude Oil Storage Tank Inspection: API 653 Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">Crude Oil Storage Tank Inspection: API 653 Walkthrough</div>
        </a>
        <a href="/sectors/gathering-system-pipeline-inspection-cost-effective" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-07-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Gathering-System Pipeline Inspection: Cost-Effective Methods</div>
          <div className="mt-2 text-sm text-gray-600">Gathering-System Pipeline Inspection: Cost-Effective Methods</div>
        </a>
        <a href="/sectors/wellhead-inspection-and-pressure-testing" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-12-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wellhead Inspection and Pressure Testing: Field Practice</div>
          <div className="mt-2 text-sm text-gray-600">Wellhead Inspection and Pressure Testing: Field Practice</div>
        </a>
        <a href="/sectors/lact-skid-and-meter-prover-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-04-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">LACT Skid and Meter Prover Inspection: What QA Should Look For</div>
          <div className="mt-2 text-sm text-gray-600">LACT Skid and Meter Prover Inspection: What QA Should Look For</div>
        </a>
        <a href="/sectors/gas-processing-plant-inspection-priority-units" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-05-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Gas Processing Plant Inspection: Priority Units and Risk-Ranked NDT</div>
          <div className="mt-2 text-sm text-gray-600">Gas Processing Plant Inspection: Priority Units and Risk-Ranked NDT</div>
        </a>
        <a href="/sectors/subsurface-safety-valve-inspection-essentials" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-08-24</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsurface Safety Valve (SSSV) Inspection Essentials</div>
          <div className="mt-2 text-sm text-gray-600">Subsurface Safety Valve (SSSV) Inspection Essentials</div>
        </a>
        <a href="/sectors/separator-and-knockout-drum-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-12-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Separator and Knock-Out Drum Inspection: Damage Mechanisms to Hunt For</div>
          <div className="mt-2 text-sm text-gray-600">Separator and Knock-Out Drum Inspection: Damage Mechanisms to Hunt For</div>
        </a>
        <a href="/sectors/midstream-station-yard-inspection-pump-compressor" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-03-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Midstream Station Yard Inspection: Pumps, Compressors, and Yard Piping</div>
          <div className="mt-2 text-sm text-gray-600">Midstream Station Yard Inspection: Pumps, Compressors, and Yard Piping</div>
        </a>
        <a href="/sectors/lease-tank-battery-inspection-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-05-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Lease Tank Battery Inspection Program for Upstream Operators</div>
          <div className="mt-2 text-sm text-gray-600">Lease Tank Battery Inspection Program for Upstream Operators</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-amber-50 border border-amber-100 rounded">
        <div className="text-sm uppercase tracking-wide text-amber-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-amber-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
