import type { MetadataRoute } from 'next';
const routes = [
  "/",
  "/api-codes",
  "/api-codes/api-510-pressure-vessels",
  "/api-codes/api-570-piping",
  "/api-codes/api-571-damage-mechanisms",
  "/api-codes/api-579-fitness-for-service",
  "/api-codes/api-580-rbi",
  "/api-codes/api-653-complete-guide",
  "/atlantis-products-services",
  "/downstream",
  "/downstream/boiler-inspection",
  "/downstream/heat-exchanger-tubes",
  "/downstream/refinery-turnaround",
  "/downstream/storage-tank-inspection",
  "/industries-and-applications",
  "/regions-and-project-planning",
  "/resources/api-code-comparison",
  "/resources/glossary",
  "/sectors",
  "/sectors/crude-oil-storage-tank-inspection-api-653-walkthrough",
  "/sectors/gas-processing-plant-inspection-priority-units",
  "/sectors/gathering-system-pipeline-inspection-cost-effective",
  "/sectors/lact-skid-and-meter-prover-inspection",
  "/sectors/lease-tank-battery-inspection-program",
  "/sectors/midstream-station-yard-inspection-pump-compressor",
  "/sectors/separator-and-knockout-drum-inspection",
  "/sectors/subsurface-safety-valve-inspection-essentials",
  "/sectors/upstream-midstream-downstream-inspection-budget-allocation",
  "/sectors/wellhead-inspection-and-pressure-testing",
  "/standards",
  "/standards/asme-section-v",
  "/standards/aws-d1-1",
  "/technology",
  "/technology/automated-ut-pipelines",
  "/technology/digital-twins-oil-gas",
  "/technology/drone-inspection",
  "/upstream",
  "/upstream/fpso-inspection",
  "/upstream/offshore-platform-ndt",
  "/upstream/subsea-pipeline"
];
export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(route => ({ url: "https://oil-gas-inspection-guide.vercel.app" + route }));
}
